server:
  port: ${RTD_TRANSACTION_MANAGER_PORT:8080}

spring:
  application:
    name: "@project.parent.artifactId@"
    version: "@project.version@"

info:
  build:
    artifact: "@project.parent.artifactId@"
    name: "@project.parent.artifactId@"
    description: "@project.description@"
    version: "@project.version@"

error-manager:
  enabled: true

meda:
  core:
    sessioncontext:
      enabled: false

logging:
  level:
    it.gov.pagopa.rtd.transaction_manager: ${LOG_LEVEL_RTD_TRANSACTION_MANAGER:DEBUG}