apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: rtdtransactionmanager 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rtdtransactionmanager 
    spec:
      containers:
        - name: rtdtransactionmanager 
          image: cstarregistry.azurecr.io/rtdtransactionmanager
          ports:
          - containerPort: 8080